config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sensors#index'

  resources :sensors do
    resources :sensor_measurements, only: [:index]
    member do
      delete 'destroy_measurements'
    end
  end
  resources :ittts

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ittt.rb
class Ittt < ApplicationRecord
  has_many :ittt_conditions, dependent: :destroy
  accepts_nested_attributes_for :ittt_conditions, reject_if: :all_blank, allow_destroy: true

  has_many :ittt_actions, dependent: :destroy
  accepts_nested_attributes_for :ittt_actions, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :ittt_conditions, presence: true
  validates :ittt_actions, presence: true

  def execute
    self.update last_evaluated_at: Time.zone.now
    if evaluate_conditions
      ittt_actions.each do |action|
        if action.send_evaluation_output?
          send_mqtt_message(action.topic, 'True')
        else
          send_mqtt_message(action.topic, action.message)
        end
      end
    else
      ittt_actions.where(send_evaluation_output: true).each do |action|
        send_mqtt_message(action.topic, 'False')
      end
    end
  end

  def evaluate_conditions
    ittt_conditions.each do |condition|
      return false unless condition.evaluate
    end
    return true
  end

  private

  def send_mqtt_message(topic, message)
    begin
      MqttClient::Connection.publish topic, message
      MqttClient::Connection.loop_write
    rescue NameError
      Rails.logger.debug 'MqttClient not defined'
    end
  end
end

app/models/ittt_action.rb
class ItttAction < ApplicationRecord
  belongs_to :ittt

  validates :topic, presence: true
  validate :message_xor_send_evaluation_output

  private

  def message_xor_send_evaluation_output
    unless message.blank? ^ !send_evaluation_output?
      errors.add(:message, 'Specify message or use message but not both.')
    end
  end
end

app/models/ittt_condition.rb
class ItttCondition < ApplicationRecord
  belongs_to :ittt
  belongs_to :sensor_1, class_name: 'Sensor'
  belongs_to :sensor_2, class_name: 'Sensor', optional: true

  validate :sensor_2_xor_comparison_value

  enum operation: {
    equal: 0,
    smaller_than: 1,
    greater_than: 2
  }

  def evaluate
    first_value = sensor_1.most_recent_measurement&.value
    second_value = sensor_2&.most_recent_measurement&.value || comparison_value

    return false if first_value.nil? || second_value.nil?

    if equal?
      return first_value == second_value
    elsif smaller_than?
      return first_value < second_value
    elsif greater_than?
      return first_value > second_value
    end
  end

  private

  def sensor_2_xor_comparison_value
    unless sensor_2_id.blank? ^ comparison_value.blank?
      errors.add(:base, "Specify sensor 2 or comparison_value not both")
    end
  end
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  has_many :sensor_measurements, dependent: :destroy

  enum sensor_type: {
    mqtt: 0,
    rest: 1
  }

  validates :name, presence: true
  validates :topic, presence: true, if: :mqtt?
  validates :url, presence: true, if: :rest?
  validates :interval, presence: true, if: :rest?
  validates :json_path, presence: true, if: :rest?

  def description
    if mqtt?
      "MQTT on topic: #{topic}"
    elsif rest?
      "REST on url: #{url}"
    end
  end

  def most_recent_measurement
    sensor_measurements.order(:created_at).last
  end
end

app/models/sensor_measurement.rb
class SensorMeasurement < ApplicationRecord
  belongs_to :sensor

  after_create :execute_ittt_on_trigger

  def value_with_text
    "#{value} recorded at #{I18n.l created_at}"
  end

  def execute_ittt_on_trigger
    Ittt.joins(:ittt_conditions).where(trigger_on_sensor_update: true).where('sensor_1_id=? OR sensor_2_id=?', sensor_id, sensor_id).each do |ittt|
      ittt.execute
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @sensors = Sensor.all
  end
end

app/controllers/ittts_controller.rb
class ItttsController < ApplicationController
  def index
    @ittts = Ittt.all
  end

  def new
    @ittt = Ittt.new
  end

  def create
    @ittt = Ittt.new permit(params)
    if @ittt.save
      flash[:success] = 'Ittt created'
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @ittt = Ittt.find params[:id]
  end

  def update
    @ittt = Ittt.find_by params.permit(:id)
    if @ittt.update permit(params)
      flash[:success] = 'Ittt updated'
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    Ittt.find_by(params.permit(:id)).destroy
    flash[:danger] = 'Ittt deleted'
    redirect_to action: 'index'
  end

  private

  def permit(params)
    params.require(:ittt).permit(
      :id,
      :name,
      :interval,
      :trigger_on_sensor_update,
      ittt_conditions_attributes: [
        :id,
        :sensor_1_id,
        :operation,
        :sensor_2_id,
        :comparison_value,
        :_destroy
      ],
      ittt_actions_attributes: [
        :id,
        :topic,
        :send_evaluation_output,
        :message,
        :_destroy
      ]
    )
  end
end

app/controllers/sensor_measurements_controller.rb
class SensorMeasurementsController < ApplicationController
  def index
    @sensor = Sensor.find params[:sensor_id]
    @sensor_measurements = @sensor.sensor_measurements.order(created_at: :desc).limit(50)
  end
end

app/controllers/sensor_mesurements_controller.rb
class SensorMesurementsController < ApplicationController
  def index
    @sensor = Sensor.find params[:sensor_id]
  end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  def index
    @sensors = Sensor.all
  end

  def new
    @sensor = Sensor.new
  end

  def create
    @sensor = Sensor.new params.require(:sensor).permit(:name, :sensor_type, :toleranz, :topic, :url, :interval, :json_path)
    if @sensor.save
      flash[:success] = 'Sensor created'
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @sensor = Sensor.find_by params.permit(:id)
  end

  def update
    @sensor = Sensor.find_by params.permit(:id)
    if @sensor.update params.require(:sensor).permit(:name, :sensor_type, :toleranz, :topic, :url, :interval, :json_path)
      flash[:success] = 'Sensor updated'
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    Sensor.find_by(params.permit(:id)).destroy
    flash[:danger] = 'Sensor deleted'
    redirect_to action: 'index'
  end

  def destroy_measurements
    @sensor = Sensor.find_by(params.permit(:id))
    @sensor.sensor_measurements.destroy_all
    flash[:danger] = 'Measurements deleted'

    redirect_to sensor_sensor_measurements_path(@sensor)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_item(name, path)
    content_tag :li, class: "nav-item #{'active' if current_page?(path)}" do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/views/ittts/_form_card.haml
.card.mt-3
  .card-header
    Ittt

  .card-body
    = simple_form_for @ittt do |f|
      = f.input :name
      = f.input :interval, hint: 'In minutes'
      = f.input :trigger_on_sensor_update, hint: ' (Ittt will be evaluated if any referenced sensors receive a new value)'
      .alert.alert-primary.my-3
        Define as many conditions as you need. You can compare sensor values to other sensor values or static values
      = f.fields_for :ittt_conditions do |condition|
        = render 'ittt_condition_fields', f: condition
      .links
        = link_to_add_association f, :ittt_conditions, class: 'btn btn-primary mt-3' do
          %i.fas.fa-plus
          Add condition
      .alert.alert-primary.my-3
        Define actions that should be triggered if all conditions return true
      = f.fields_for :ittt_actions do |action|
        = render 'ittt_action_fields', f: action
      .links
        = link_to_add_association f, :ittt_actions, class: 'btn btn-primary mt-3' do
          %i.fas.fa-plus
          Add action

      = f.submit class: 'btn btn-primary mt-3 float-end'

app/views/ittts/_ittt_action_fields.haml
.nested-fields
  .card.mt-3
    .card-body
      = link_to_remove_association f, class: 'float-end text-danger' do
        %i.fa.fa-trash-alt
      = f.input :topic
      = f.input :message
      %p
        = '- or -'
      = f.input :send_evaluation_output

app/views/ittts/_ittt_card.haml
.col.mb-4
  .card
    .card-body
      %h5.card-title
        = ittt.name
      %p.card-text.ittt-last-updated
        = I18n.l ittt.last_evaluated_at

      = link_to edit_ittt_path(ittt), class: 'card-link' do
        %i.fas.fa-edit
        Edit

app/views/ittts/_ittt_condition_fields.haml
.nested-fields
  .card.mt-3
    .card-body
      = link_to_remove_association f, class: 'float-end text-danger' do
        %i.fa.fa-trash-alt
      .d-flex.align-items-center.justify-content-between
        .col.p-1
          = f.association :sensor_1
        .col.p-1
          = f.input :operation, collection: ItttCondition.operations.symbolize_keys.keys, include_blank: false, include_hidden: false
        .col.p-1
          = f.association :sensor_2
          .text-center
            or
          = f.input :comparison_value

app/views/ittts/edit.haml
= render partial: 'form_card'

app/views/ittts/index.haml
.card.mt-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    Ittts
    = button_to 'Add', new_ittt_path, class: 'btn btn-primary', method: :get

  .card-body
    .row.row-cols-1.row-cols-sm-2.row-cols-md-3
      - @ittts.each do |ittt|
        = render partial: 'ittt_card', locals: {ittt: ittt}

app/views/ittts/new.haml
= render partial: 'form_card'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IotIttt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title IoT ittt
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag

    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.bg-dark
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      .container-fluid
        %a.navbar-brand
          IoT ittt
        %button.navbar-toggler{ data: {bs: {toggle: 'collapse', target: '#navbarToggler'}}, aria: {controls: 'navbarToggler', expanded: false, label: 'Toggle navigation'}, type: 'button'}
          %span.navbar-toggler-icon
        .collapse.navbar-collapse{ id: 'navbarToggler' }
          %ul.navbar-nav.me-auto.mb-2.mb-lg-0
            = nav_item 'Home', root_path
            = nav_item 'Ittt', ittts_path

    .container{id: :flashbox }
      - flash.each do |key, value|
        .alert.alert-dismissible.mt-3{class: "alert-#{key}", role: 'alert'}
          = value
          %button.btn-close.close{data: {bs: {dismiss: 'alert'}}, aria: {label: 'Close'}, type: 'button'}

      = yield

app/views/sensor_measurements/index.haml
.card.my-3
  = line_chart @sensor_measurements.map{|m| [m.created_at, m.value]}.to_h

.card.mb-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    = "Measurement for #{@sensor.name}"
    = button_to 'Delete', destroy_measurements_sensor_path(@sensor), class: 'btn btn-danger', method: :delete
  .table-responsive
    %table.table
      %tr
        %th
          Value
        %th
          Time
        %th
      - @sensor_measurements.each do |measurement|
        %tr
          %td
            = measurement.value
          %td
            = I18n.l measurement.created_at

app/views/sensor_mesurements/index.haml
.card.mt-3
  %h5.card-header
    = "Mesurements for #{@sensor.name}"
  .table-responsive
    %table.table
      %tr
        %th
          Value
        %th
          Time
        %th
      - @sensor.sensor_mesurements.each do |mesurement|
        %tr
          %td
            = mesurement.value
          %td
            = I18n.l mesurement.created_at

app/views/sensors/_form_card.haml
.card.mt-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    Sensor
    .row
      - if @sensor.id.present?
        .col.p-0
          = button_to 'Delete', sensor_path(@sensor), class: 'btn btn-danger', method: :delete
      .col
        = button_to 'Cancel', sensors_path, class: 'btn btn-secondary', method: :get

  .card-body
    = simple_form_for @sensor do |f|
      = f.input :name
      = f.input :sensor_type, collection: Sensor.sensor_types.symbolize_keys.keys, include_blank: false, include_hidden: false
      = f.input :toleranz, hint: 'Values +/- the toleranz will not be logged as new values'
      = f.input :topic, hint: 'Only for MQTT'
      = f.input :url, hint: 'Only for REST'
      = f.input :interval, hint: 'Only for REST, in minutes'
      = f.input :json_path, hint: 'Only for REST. This path will be used to find the correct value in the result json'
      = f.submit 'Save', class: 'btn btn-primary mt-2'

app/views/sensors/_sensor_card.haml
.col.mb-4
  .card.sensor-card{data: {sensor_id: sensor.id}}
    .card-body
      %h5.card-title
        = sensor.name
      %h6.card-subtitle.mb-2.text-muted
        = sensor.description
      %p.card-text.sensor-value
        = sensor.most_recent_measurement&.value_with_text
      = link_to edit_sensor_path(sensor), class: 'card-link' do
        %i.fas.fa-edit
        Edit
      = link_to sensor_sensor_measurements_path(sensor), class: 'card-link' do
        %i.fas.fa-search
        Show measurements

app/views/sensors/index.haml
.card.mt-3
  %h5.card-header.d-flex.justify-content-between.align-items-center
    Sensors
    = button_to 'Add', new_sensor_path, class: 'btn btn-primary', method: :get

  .card-body
    .row.row-cols-1.row-cols-sm-2.row-cols-md-3
      - @sensors.each do |sensor|
        = render partial: 'sensor_card', locals: {sensor: sensor}